//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Sloganeer.rc
//
#define IDR_MAINFRAME                   101
#define IDD_ABOUTBOX                    102
#define IDD_HELPBOX                     103
#define IDD_PARAMS                      104
#define IDD_PROGRESS                    105
#define IDD_SLOGANEER_DIALOG            106
#define IDS_ABOUTBOX                    200
#define IDS_APP_ERR_CANT_CREATE_APP_DATA_FOLDER 201
#define IDS_APP_LICENSE                 202
#define IDS_APP_UNKNOWN_SYSTEM_ERROR    203
#define IDS_CSV_ERR_LOCATION            204
#define IDS_ERR_BAD_COLUMN_NAME         205
#define IDS_ERR_BAD_ESCAPE_SEQ          206
#define IDS_ERR_CANT_INIT_COM           207
#define IDS_ERR_CAPTURE_FRAME_SIZE_CHANGE 208
#define IDS_ERR_PARAM_INVALID           209
#define IDS_ERR_PARAM_MISSING           210
#define IDS_ERR_PARAM_RANGE             211
#define IDS_ERR_PIPE_TIMEOUT            212
#define IDS_ERR_UNKNOWN_FLAG            213
#define IDS_FLAG_EXAMPLE_bgclr          214
#define IDS_FLAG_EXAMPLE_bgclr2         215
#define IDS_FLAG_EXAMPLE_bgclr3         216
#define IDS_FLAG_EXAMPLE_fontname       217
#define IDS_FLAG_EXAMPLE_fontsize       218
#define IDS_FLAG_EXAMPLE_fontwt         219
#define IDS_FLAG_EXAMPLE_transdur       220
#define IDS_FLAG_HELP_bgclr             221
#define IDS_FLAG_HELP_bgfrq             222
#define IDS_FLAG_HELP_bgpal             223
#define IDS_FLAG_HELP_drawclr           224
#define IDS_FLAG_HELP_drawfrq           225
#define IDS_FLAG_HELP_drawpal           226
#define IDS_FLAG_HELP_easing            227
#define IDS_FLAG_HELP_fontname          228
#define IDS_FLAG_HELP_fontsize          229
#define IDS_FLAG_HELP_fontwt            230
#define IDS_FLAG_HELP_fullscr           231
#define IDS_FLAG_HELP_help              232
#define IDS_FLAG_HELP_holddur           233
#define IDS_FLAG_HELP_license           234
#define IDS_FLAG_HELP_markdown          235
#define IDS_FLAG_HELP_nowrap            236
#define IDS_FLAG_HELP_outdur            237
#define IDS_FLAG_HELP_pausedur          238
#define IDS_FLAG_HELP_recdur            239
#define IDS_FLAG_HELP_record            240
#define IDS_FLAG_HELP_recrate           241
#define IDS_FLAG_HELP_recsize           242
#define IDS_FLAG_HELP_seed              243
#define IDS_FLAG_HELP_seqtext           244
#define IDS_FLAG_HELP_text              245
#define IDS_FLAG_HELP_transdur          246
#define IDS_FLAG_HELP_transtyp          247
#define IDS_FULL_SCREEN                 248
#define IDS_HELP                        249
#define IDS_HELP_EXAMPLES               250
#define IDS_HELP_PARAM_path             251
#define IDS_HELP_USAGE                  252
#define IDS_IMAGE_SEQ_OVERWRITE_WARN    253
#define IDS_NONE                        254
#define IDS_PARAMS                      255
#define IDS_TT_CLOCK                    256
#define IDS_TT_CONVERGE_HORZ            257
#define IDS_TT_CONVERGE_VERT            258
#define IDS_TT_ELEVATOR                 259
#define IDS_TT_EXPLODE                  260
#define IDS_TT_FADE                     261
#define IDS_TT_IRIS                     262
#define IDS_TT_MELT                     263
#define IDS_TT_RAND_TILE                264
#define IDS_TT_RAND_TYPE                265
#define IDS_TT_REVEAL_LR                266
#define IDS_TT_REVEAL_TB                267
#define IDS_TT_SCALE_BOTH               268
#define IDS_TT_SCALE_HORZ               269
#define IDS_TT_SCALE_SPIN               270
#define IDS_TT_SCALE_VERT               271
#define IDS_TT_SCROLL_BT                272
#define IDS_TT_SCROLL_LR                273
#define IDS_TT_SCROLL_RL                274
#define IDS_TT_SCROLL_TB                275
#define IDS_TT_SKEW                     276
#define IDS_TT_SUBMARINE                277
#define IDS_TT_TUMBLE                   278
#define IDS_TT_TYPEWRITER               279
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_VERSION               1002
#define IDC_HELP_EDIT                   1003
#define IDC_PARAMS_COLOR_BKGND          1004
#define IDC_PARAMS_COLOR_BKGND_ALPHA    1005
#define IDC_PARAMS_COLOR_DRAW           1006
#define IDC_PARAMS_COLOR_DRAW_ALPHA     1007
#define IDC_PARAMS_DUR_HOLD             1008
#define IDC_PARAMS_DUR_IN               1009
#define IDC_PARAMS_DUR_OUT              1010
#define IDC_PARAMS_DUR_PAUSE            1011
#define IDC_PARAMS_FONT_NAME            1012
#define IDC_PARAMS_FONT_SIZE            1013
#define IDC_PARAMS_FONT_WEIGHT          1014
#define IDC_PARAMS_IMMEDIATE_MODE       1015
#define IDC_PARAMS_PLAY_MODE_0          1016
#define IDC_PARAMS_PLAY_MODE_1          1017
#define IDC_PARAMS_PLAY_MODE_2          1018
#define IDC_PARAMS_SLOGAN               1019
#define IDC_PARAMS_SLOGAN_NEW           1020
#define IDC_PARAMS_TRANS_TYPE_IN        1021
#define IDC_PARAMS_TRANS_TYPE_OUT       1022
#define IDC_PARAMS_TRIGGER_GO           1023
#define IDC_PARAMS_TRIGGER_TYPE_0       1024
#define IDC_PARAMS_TRIGGER_TYPE_1       1025
#define IDC_PROGRESS                    1026
#define IDC_PROGRESS_PERCENT            1027

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        280
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
